

```{r}
library("fpp2", lib.loc="~/R/win-library/4.0")
```


```{r}
tr_PM10_24h_00 <- read.csv("~/It Academy/Data Science/Aire/tr_PM10_24h_00.csv", row.names=1)
tr_PM10_24h_01 <- read.csv("~/It Academy/Data Science/Aire/tr_PM10_24h_01.csv", row.names=1)
tr_PM10_24h_02 <- read.csv("~/It Academy/Data Science/Aire/tr_PM10_24h_02.csv", row.names=1)
tr_PM10_24h_03 <- read.csv("~/It Academy/Data Science/Aire/tr_PM10_24h_03.csv", row.names=1)
tr_PM10_24h_04 <- read.csv("~/It Academy/Data Science/Aire/tr_PM10_24h_04.csv", row.names=1)
tr_PM10_24h_05 <- read.csv("~/It Academy/Data Science/Aire/tr_PM10_24h_05.csv", row.names=1)
tr_PM10_24h_06 <- read.csv("~/It Academy/Data Science/Aire/tr_PM10_24h_06.csv", row.names=1)
tr_PM10_24h_07 <- read.csv("~/It Academy/Data Science/Aire/tr_PM10_24h_07.csv", row.names=1)
tr_PM10_24h_08 <- read.csv("~/It Academy/Data Science/Aire/tr_PM10_24h_08.csv", row.names=1)
tr_PM10_24h_09 <- read.csv("~/It Academy/Data Science/Aire/tr_PM10_24h_09.csv", row.names=1)
tr_PM10_24h_10 <- read.csv("~/It Academy/Data Science/Aire/tr_PM10_24h_10.csv", row.names=1)
tr_PM10_24h_11 <- read.csv("~/It Academy/Data Science/Aire/tr_PM10_24h_11.csv", row.names=1)
tr_PM10_24h_12 <- read.csv("~/It Academy/Data Science/Aire/tr_PM10_24h_12.csv", row.names=1)
tr_PM10_24h_13 <- read.csv("~/It Academy/Data Science/Aire/tr_PM10_24h_13.csv", row.names=1)
tr_PM10_24h_14 <- read.csv("~/It Academy/Data Science/Aire/tr_PM10_24h_14.csv", row.names=1)
tr_PM10_24h_15 <- read.csv("~/It Academy/Data Science/Aire/tr_PM10_24h_15.csv", row.names=1)
tr_PM10_24h_16 <- read.csv("~/It Academy/Data Science/Aire/tr_PM10_24h_16.csv", row.names=1)
tr_PM10_24h_17 <- read.csv("~/It Academy/Data Science/Aire/tr_PM10_24h_17.csv", row.names=1)
tr_PM10_24h_18 <- read.csv("~/It Academy/Data Science/Aire/tr_PM10_24h_18.csv", row.names=1)
tr_PM10_24h_19 <- read.csv("~/It Academy/Data Science/Aire/tr_PM10_24h_19.csv", row.names=1)
tr_PM10_24h_20 <- read.csv("~/It Academy/Data Science/Aire/tr_PM10_24h_20.csv", row.names=1)
tr_PM10_24h_21 <- read.csv("~/It Academy/Data Science/Aire/tr_PM10_24h_21.csv", row.names=1)
tr_PM10_24h_22 <- read.csv("~/It Academy/Data Science/Aire/tr_PM10_24h_22.csv", row.names=1)
tr_PM10_24h_23 <- read.csv("~/It Academy/Data Science/Aire/tr_PM10_24h_23.csv", row.names=1)
```

```{r}
mod.tr_PM10_24h_00 <- auto.arima(tr_PM10_24h_00, trace=TRUE, allowdrift=FALSE)
mod.tr_PM10_24h_01 <- auto.arima(tr_PM10_24h_01, trace=TRUE, allowdrift=FALSE)
mod.tr_PM10_24h_02 <- auto.arima(tr_PM10_24h_02, trace=TRUE, allowdrift=FALSE)
mod.tr_PM10_24h_03 <- auto.arima(tr_PM10_24h_03, trace=TRUE, allowdrift=FALSE)
mod.tr_PM10_24h_04 <- auto.arima(tr_PM10_24h_04, trace=TRUE, allowdrift=FALSE)
mod.tr_PM10_24h_05 <- auto.arima(tr_PM10_24h_05, trace=TRUE, allowdrift=FALSE)
mod.tr_PM10_24h_06 <- auto.arima(tr_PM10_24h_06, trace=TRUE, allowdrift=FALSE)
mod.tr_PM10_24h_07 <- auto.arima(tr_PM10_24h_07, trace=TRUE, allowdrift=FALSE)
mod.tr_PM10_24h_08 <- auto.arima(tr_PM10_24h_08, trace=TRUE, allowdrift=FALSE)
mod.tr_PM10_24h_09 <- auto.arima(tr_PM10_24h_09, trace=TRUE, allowdrift=FALSE)
mod.tr_PM10_24h_10 <- auto.arima(tr_PM10_24h_10, trace=TRUE, allowdrift=FALSE)
mod.tr_PM10_24h_11 <- auto.arima(tr_PM10_24h_11, trace=TRUE, allowdrift=FALSE)
mod.tr_PM10_24h_12 <- auto.arima(tr_PM10_24h_12, trace=TRUE, allowdrift=FALSE)
mod.tr_PM10_24h_13 <- auto.arima(tr_PM10_24h_13, trace=TRUE, allowdrift=FALSE)
mod.tr_PM10_24h_14 <- auto.arima(tr_PM10_24h_14, trace=TRUE, allowdrift=FALSE)
mod.tr_PM10_24h_15 <- auto.arima(tr_PM10_24h_15, trace=TRUE, allowdrift=FALSE)
mod.tr_PM10_24h_16 <- auto.arima(tr_PM10_24h_16, trace=TRUE, allowdrift=FALSE)
mod.tr_PM10_24h_17 <- auto.arima(tr_PM10_24h_17, trace=TRUE, allowdrift=FALSE)
mod.tr_PM10_24h_18 <- auto.arima(tr_PM10_24h_18, trace=TRUE, allowdrift=FALSE)
mod.tr_PM10_24h_19 <- auto.arima(tr_PM10_24h_19, trace=TRUE, allowdrift=FALSE)
mod.tr_PM10_24h_20 <- auto.arima(tr_PM10_24h_20, trace=TRUE, allowdrift=FALSE)
mod.tr_PM10_24h_21 <- auto.arima(tr_PM10_24h_21, trace=TRUE, allowdrift=FALSE)
mod.tr_PM10_24h_22 <- auto.arima(tr_PM10_24h_22, trace=TRUE, allowdrift=FALSE)
mod.tr_PM10_24h_23 <- auto.arima(tr_PM10_24h_23, trace=TRUE, allowdrift=FALSE)
```

